---
# Functions and routines associated with Enasis Network Orchestrations.

# This file is part of Enasis Network software eco-system. Distribution
# is permitted, for more information consult the project license file.






- name: Clone the configuration from repository

  ansible.builtin.git:
    repo: '{{ enhomie_repo_path }}'
    dest: >-
      {{ enhomie_directory -}}
      /repos/{{ enhomie_unique }}
    depth: 1
    version: '{{ enhomie_repo_version }}'
    force: true

  when: enhomie_repo_path

  notify: restart enhomie

  tags: always






- name: Template the service configuration file

  ansible.builtin.template:
    src: config.j2
    dest: >-
      {{ enhomie_directory -}}
      /config/{{ enhomie_unique }}.yml
    owner: '{{ enhomie_user }}'
    group: '{{ enhomie_group }}'
    mode: '0600'

  become: true

  notify: restart enhomie

  tags: always
