---
# Functions and routines associated with Enasis Network Orchestrations.

# This file is part of Enasis Network software eco-system. Distribution
# is permitted, for more information consult the project license file.






- name: Create directories for related package

  file:
    path: '{{ item.path }}'
    owner: '{{ enhomie.user }}'
    group: '{{ enhomie.group }}'
    mode: '0700'
    state: directory

  loop:
    - path: '{{ basedir }}'
    - path: '{{ basedir }}/cache'
    - path: '{{ basedir }}/config'
    - path: '{{ basedir }}/logs'
    - path: '{{ basedir }}/repos'

  loop_control:
    label: '{{ item.path }}'

  vars:
    basedir: '{{ enhomie.directory }}'

  tags: always
