---
# Functions and routines associated with Enasis Network Orchestrations.

# This file is part of Enasis Network software eco-system. Distribution
# is permitted, for more information consult the project license file.






- name: Assert conditions for downstream tasks

  ansible.builtin.assert:
    that:

      - >-  # only specific hosts
        'roles_enhomie' in groups

  tags: always






- name: Include downstream tasks within roles

  ansible.builtin.include_tasks: >-
    tasks/params.yml

  tags: always



- name: Declare relevant playbook variables

  ansible.builtin.set_fact:
    enhomie_service: >-
      enhomie-service@{{ enhomie_unique }}

  tags: always






- name: Include downstream tasks within roles

  ansible.builtin.include_tasks: >-
    tasks/overview.yml

  tags: overview



- name: Include downstream tasks within roles

  ansible.builtin.include_tasks: >-
    tasks/folders.yml

  tags:
    - install
    - reinstall



- name: Include downstream tasks within roles

  ansible.builtin.include_tasks: >-
    tasks/state.yml

  tags: reinstall



- name: Include downstream tasks within roles

  ansible.builtin.include_tasks: >-
    tasks/package.yml

  tags:
    - install
    - reinstall



- name: Include downstream tasks within roles

  ansible.builtin.include_tasks: >-
    tasks/config.yml

  tags:
    - install
    - reinstall
    - configure



- name: Include downstream tasks within roles

  ansible.builtin.include_tasks: >-
    tasks/systemd.yml

  tags:
    - install
    - reinstall



- name: Include downstream tasks within roles

  ansible.builtin.include_tasks: >-
    tasks/state.yml

  tags:
    - state-restarted
    - state-stopped
    - state-started
