---
# Functions and routines associated with Enasis Network Orchestrations.

# This file is part of Enasis Network software eco-system. Distribution
# is permitted, for more information consult the project license file.






- name: Assert conditions for downstream tasks

  ansible.builtin.assert:
    that:

      - >-  # only specific hosts
        'roles_enhomie' in groups

  tags: always






- name: Declare relevant playbook variables

  ansible.builtin.set_fact:

    enhomie_unique: >-
      {{ enhomie_unique | default(none) }}
    enhomie_directory: >-
      {{ enhomie_directory | default(none) }}
    enhomie_user: >-
      {{ enhomie_user | default(none) }}
    enhomie_group: >-
      {{ enhomie_group | default(none) }}
    enhomie_python: >-
      {{ enhomie_python | default(none) }}
    enhomie_package: >-
      {{ enhomie_package | default(none) }}
    enhomie_version: >-
      {{ enhomie_version | default(none) }}
    enhomie_repo_path: >-
      {{ enhomie_repo_path | default(none) }}
    enhomie_repo_version: >-
      {{ enhomie_repo_version | default(none) }}
    enhomie_config: >-
      {{ enhomie_config | default(none) }}
    enhomie_logging: >-
      {{ enhomie_logging | default(none) }}
    enhomie_console: >-
      {{ enhomie_console | default(none) }}

  tags: always



- name: Declare relevant playbook variables

  ansible.builtin.set_fact:

    enhomie_vars: >-
      {%- set values = {} -%}
      {%- for key, value in vars.items() -%}
      {%-   if key.startswith('enhomie_') -%}
      {%-     do values.update({key: value}) -%}
      {%-   endif -%}
      {%- endfor -%}
      {{- values | sort_dict -}}

  tags: always



- name: Validate role variables using Pydantic

  enhomie_params:
    params: '{{ enhomie_vars }}'

  tags: always






- name: Include downstream tasks within roles

  ansible.builtin.include_tasks: >-
    tasks/overview.yml

  tags: overview



- name: Include downstream tasks within roles

  ansible.builtin.include_tasks: >-
    tasks/folders.yml

  tags: install



- name: Include downstream tasks within roles

  ansible.builtin.include_tasks: >-
    tasks/package.yml

  tags: install



- name: Include downstream tasks within roles

  ansible.builtin.include_tasks: >-
    tasks/config.yml

  tags:
    - install
    - configure
