---
# Functions and routines associated with Enasis Network Orchestrations.

# This file is part of Enasis Network software eco-system. Distribution
# is permitted, for more information consult the project license file.






- name: Install the package in the virtual env

  ansible.builtin.pip:
    name: '{{ enhomie.package }}'
    virtualenv: >-
      {{ enhomie.directory }}/venv
    virtualenv_command: >-
      {{ enhomie.python }} -m venv
    state: latest

  tags: always
