---
# Functions and routines associated with Enasis Network Orchestrations.

# This file is part of Enasis Network software eco-system. Distribution
# is permitted, for more information consult the project license file.






- name: Remove virtual env when doing reinstall

  file:
    path: '{{ enhomie_directory }}/venv'
    state: absent

  become: yes

  tags: reinstall






- name: Install the package in the virtual env

  ansible.builtin.pip:
    name: '{{ enhomie_package }}'
    virtualenv: >-
      {{ enhomie_directory }}/venv
    virtualenv_command: >-
      {{ enhomie_python }} -m venv
    state: latest
    version: >-
      {{ enhomie_version | default(omit) }}

  become_user: '{{ enhomie_user }}'

  tags: always
