---



systems:


  ######################
  ## Default Template ##
  ######################
  template_default:
    enable: false
    domain: enasis.net
    display: Default Template


    #######################
    ## Ansible Variables ##
    #######################
    ansible:
      ansible_host: '{{ inventory_hostname }}'
      ansible_user: root


      ###########################
      ## Certificate Authority ##
      ###########################
      sslca_certificate:
        - name: '{{ inventory_hostname }}'
          kind: server
          common: '{{ orche_system.fqdn }}'
          parent: system
