---



systems:


  ######################
  ## Default Template ##
  ######################
  template_default:
    enable: false
    domain: enasis.net
    display: Default Template


    #######################
    ## Ansible Variables ##
    #######################
    ansible:
      ansible_host: '{{ inventory_hostname }}'
      ansible_user: root
