---
# Functions and routines associated with Enasis Network Orchestrations.

# This file is part of Enasis Network software eco-system. Distribution
# is permitted, for more information consult the project license file.






- name: Information about the inventory hosts

  ansible.builtin.debug:
    msg:

      ansible:
        host: '{{ ansible_host | default }}'
        user: '{{ ansible_user | default }}'
        groups: '{{ group_names }}'

      orche: >-
        {%- if orche | default -%}
        {%-   set hostname = inventory_hostname -%}
        {%-   set systems = orche.childs.systems -%}
        {%-   set system = systems[hostname] -%}
        {{-   {'name': system.name,
               'domain': system.params.domain} -}}
        {%- else -%}
        'Not an OrcheSystem'
        {%- endif -%}

  when:

    - >-  # target is not localhost
      inventory_hostname != "localhost"

  tags: always
