---
# Functions and routines associated with Enasis Network Orchestrations.

# This file is part of Enasis Network software eco-system. Distribution
# is permitted, for more information consult the project license file.






- name: Information about the inventory hosts

  ansible.builtin.ping:

  when:

    - >-  # target is not localhost
      inventory_hostname != "localhost"

  tags: always
