---
# Functions and routines associated with Enasis Network Orchestrations.

# This file is part of Enasis Network software eco-system. Distribution
# is permitted, for more information consult the project license file.






- name: Clone the configuration from repository

  ansible.builtin.git:
    repo: '{{ enrobie_repo_path }}'
    dest: >-
      {{ enrobie_directory -}}
      /repos/{{ enrobie_unique }}
    depth: 1
    version: '{{ enrobie_repo_version }}'
    force: true

  when: enrobie_repo_path

  notify: restart enrobie

  tags: always






- name: Template the service configuration file

  ansible.builtin.template:
    src: config.j2
    dest: >-
      {{ enrobie_directory -}}
      /config/{{ enrobie_unique }}.yml
    owner: '{{ enrobie_user }}'
    group: '{{ enrobie_group }}'
    mode: '0600'

  become: true

  notify: restart enrobie

  tags: always
