---
# Functions and routines associated with Enasis Network Orchestrations.

# This file is part of Enasis Network software eco-system. Distribution
# is permitted, for more information consult the project license file.






- name: Assert conditions for downstream tasks

  ansible.builtin.assert:
    that:

      - >-  # only specific hosts
        'roles_enrobie' in groups

  tags: always






- name: Declare relevant playbook variables

  ansible.builtin.set_fact:

    enrobie_unique: >-
      {{ enrobie_unique | default(none) }}
    enrobie_directory: >-
      {{ enrobie_directory | default(none) }}
    enrobie_user: >-
      {{ enrobie_user | default(none) }}
    enrobie_group: >-
      {{ enrobie_group | default(none) }}
    enrobie_python: >-
      {{ enrobie_python | default(none) }}
    enrobie_package: >-
      {{ enrobie_package | default(none) }}
    enrobie_version: >-
      {{ enrobie_version | default(none) }}
    enrobie_repo_path: >-
      {{ enrobie_repo_path | default(none) }}
    enrobie_repo_version: >-
      {{ enrobie_repo_version | default(none) }}
    enrobie_config: >-
      {{ enrobie_config | default(none) }}
    enrobie_logging: >-
      {{ enrobie_logging | default(none) }}
    enrobie_console: >-
      {{ enrobie_console | default(none) }}

  tags: always



- name: Declare relevant playbook variables

  ansible.builtin.set_fact:

    enrobie_vars: >-
      {%- set values = {} -%}
      {%- for key, value in vars.items() -%}
      {%-   if key.startswith('enrobie_') -%}
      {%-     do values.update({key: value}) -%}
      {%-   endif -%}
      {%- endfor -%}
      {{- values | sort_dict -}}

  tags: always



- name: Validate role variables using Pydantic

  enrobie_params:
    params: '{{ enrobie_vars }}'

  tags: always






- name: Include downstream tasks within roles

  ansible.builtin.include_tasks: >-
    tasks/overview.yml

  tags: overview



- name: Include downstream tasks within roles

  ansible.builtin.include_tasks: >-
    tasks/folders.yml

  tags: install



- name: Include downstream tasks within roles

  ansible.builtin.include_tasks: >-
    tasks/package.yml

  tags: install



- name: Include downstream tasks within roles

  ansible.builtin.include_tasks: >-
    tasks/config.yml

  tags:
    - install
    - configure
