---
# Functions and routines associated with Enasis Network Orchestrations.

# This file is part of Enasis Network software eco-system. Distribution
# is permitted, for more information consult the project license file.






- name: Information about the inventory hosts

  ansible.builtin.debug:
    msg: >-
      {%- set values = {} -%}
      {%- for key, value in vars.items() -%}
      {%-   if key.startswith('enrobie_') -%}
      {%-     do values.update({key: value}) -%}
      {%-   endif -%}
      {%- endfor -%}
      {{- values | sort_dict -}}

  when:

    - >-  # target is not localhost
      inventory_hostname != "localhost"

  tags: always
